# Generated by Django 4.2.1 on 2023-07-01 20:47

import blog.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='', max_length=200)),
                ('title_tr', models.CharField(default='', max_length=200)),
                ('title_no', models.CharField(default='', max_length=200)),
                ('content_en', models.TextField(default='')),
                ('content_tr', models.TextField(default='')),
                ('content_no', models.TextField(default='')),
                ('tags_en', models.CharField(default='', max_length=200)),
                ('tags_tr', models.CharField(default='', max_length=200)),
                ('tags_no', models.CharField(default='', max_length=200)),
                ('slug_en', models.SlugField(blank=True, unique=True)),
                ('slug_tr', models.SlugField(blank=True, unique=True)),
                ('slug_no', models.SlugField(blank=True, unique=True)),
                ('blog_image', models.ImageField(upload_to=blog.utils.get_random_filename)),
                ('image_filter', models.CharField(choices=[('none', 'None'), ('blur', 'Blur'), ('brightness', 'Brightness'), ('contrast', 'Contrast'), ('grayscale', 'Grayscale'), ('huerotate', 'Huerotate'), ('invert', 'Invert'), ('opacity', 'Opacity'), ('saturate', 'Saturate'), ('sepia', 'Sepia')], default='none', max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=255)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
