# Generated by Django 4.2.1 on 2023-06-10 11:04

import blog.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('blog_image', models.ImageField(upload_to=blog.utils.get_random_filename)),
                ('image_filter', models.CharField(choices=[('none', 'None'), ('blur', 'Blur'), ('brightness', 'Brightness'), ('contrast', 'Contrast'), ('grayscale', 'Grayscale'), ('huerotate', 'Huerotate'), ('invert', 'Invert'), ('opacity', 'Opacity'), ('saturate', 'Saturate'), ('sepia', 'Sepia')], default='none', max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=255)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
