# Generated by Django 4.2.1 on 2023-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_no',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_tr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_en',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_no',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_tr',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags_no',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags_tr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_no',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(default='', max_length=200),
        ),
    ]
