# Generated by Django 4.2.1 on 2023-07-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_no',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_tr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags_tr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=200),
        ),
    ]
